# .pre-commit-config.yaml
exclude: '^tests/'

repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black"]
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3.11
        args: ["--line-length", "88"]
        exclude: tests/
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        files: src/
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        args: ['--install-types', '--non-interactive']
        additional_dependencies: ['numpy', 'matplotlib']
        exclude: '^tests/'
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.8
    hooks:
      - id: bandit
        args: ["--skip", "B106", "--exclude", "tests"]
        files: src/
