stages:
  preprocess:
    cmd : python ./src/preprocess.py data
    deps:
      - src/preprocess.py
      - data/raw/train.txt
      - data/raw/val.txt
      - data/raw/test.txt
    outs:
      - data/preprocess/X_train.npy
      - data/preprocess/y_train.npy
      - data/preprocess/X_val.npy
      - data/preprocess/y_val.npy
      - data/preprocess/X_test.npy
      - data/preprocess/y_test.npy
      - data/preprocess/char_index.json
  train:
    cmd:
      - python ./src/train.py ./data ./src/params.yaml
    deps:
      - src/model_definition.py
      - src/train.py
      - data/preprocess/X_train.npy
      - data/preprocess/y_train.npy
      - data/preprocess/X_val.npy
      - data/preprocess/y_val.npy
      - data/preprocess/char_index.json
    outs:
      - models/trained_model.keras
  test:
    cmd: python ./src/predict.py data
    deps:
      - src/predict.py
      - models/trained_model.keras
      - data/preprocess/X_test.npy
      - data/preprocess/y_test.npy
    outs:
      - reports/results/results.txt
      - reports/results/confusion_matrix.pdf
      

artifacts:
  phishing-detector:
    path: models/trained_model.keras
    type: model
    