batch_test: 5000
batch_train: 5000
categories:
- phishing
- legitimate
char_index: null
dataset_dir: data/raw 
embedding_dimension: 50
epoch: 1
loss_function: binary_crossentropy
optimizer: adam
sequence_length: 200
